FROM elixir:alpine

# install build dependencies
RUN apk add --no-cache build-base git python3

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# install mix dependencies
COPY mix.exs mix.lock ./
COPY config config
RUN mix do deps.get, deps.compile

COPY priv priv
# compile and build release
COPY lib lib
# uncomment COPY if rel/ exists
# COPY rel rel
COPY docker_dev_start.sh docker_dev_start.sh

EXPOSE 4000
